### ISSUE TITLE
Forget to return result of Logarithmic Map on Vector Heat Method

### ISSUE THREAD

**Issue by liwind** [nmwsharp/geometry-central#114]
Forget to return result of Logarithmic Map on Vector Heat Method, when point on **edge**.
https://github.com/nmwsharp/geometry-central/blob/1739a2c05f58f70e4e29f2411410dec5ae506eb3/src/surface/vector_heat_method.cpp#L455-L462

`return resultMap; ` should add before `break;`(line 456) just like point on **face**(line 489)
https://github.com/nmwsharp/geometry-central/blob/1739a2c05f58f70e4e29f2411410dec5ae506eb3/src/surface/vector_heat_method.cpp#L489

**Comment by nmwsharp** [comment]
Thank you for pointing this out! You are totally right, this looks like a bug.

I just pushed a quick fix in 2ceecc9. Feel free to reopen this issue if it seems like there are further problems.
