### ISSUE TITLE
Documentation: Broken link in geometry/quantities

### ISSUE THREAD

**Issue by hoskillua** [nmwsharp/geometry-central#115]
Hi everyone,
I was going through GC's documentation and noticed that the link below leads to 404 not found. 

![image](https://user-images.githubusercontent.com/47090776/164308855-dae66c48-eb6f-4bb5-b50f-7627e9a03962.png)

At first I thought of fixing it myself. but I could not find the video linked anywhere here.

**Comment by keenancrane** [comment]
Here’s the link: https://youtu.be/NlU1m-OfumE
