### ISSUE TITLE
exact geodesics seems to go wrong on mesh with boundary

### ISSUE THREAD

**Issue by henryliuw** [nmwsharp/geometry-central#119]
Hi I am trying to use the exact geodesic methods, the method worked well on mesh with boundary. When I tried to use a mesh with boundary, which I simply call the following:

`VertexData<double> distToSource = exactGeodesicDistance(*mesh, *geometry, mesh->vertex(1));`

It seems the program never exits the `GeodesicAlgorithmExact::propagate` function call and I notice on [exact_geodesics.cpp#L420](https://github.com/nmwsharp/geometry-central/blob/a66e4acec75e8f70924c9b0270bf49de1a830b0d/src/surface/exact_geodesics.cpp#L420), the size of m_queue keeps growing and never stopped.

I am still trying to locate more specifically where is the error. The method worked well on mesh with boundary.

**Comment by henryliuw** [comment]
I found the problem is somehow caused by the IO method. If I read the mesh as SurfaceMesh it goes well, instead if I read it as ManifoldSurfaceMesh it goes wrong. Here is a minimal example:

```
#include "geometrycentral/surface/meshio.h"
#include "geometrycentral/surface/exact_geodesics.h"
#include <iostream>

using namespace geometrycentral;
using namespace geometrycentral::surface;

int main(int argc, char **argv) {
	std::unique_ptr<SurfaceMesh> mesh; // if I use std::unique_ptr<ManifoldSurfaceMesh> mesh together with readManifoldSurfaceMesh it's also an error
	std::unique_ptr<VertexPositionGeometry> geometry;
	std::tie(mesh, geometry) = readManifoldSurfaceMesh("small_disk.obj"); // this line goes wrong
	//std::tie(mesh, geometry) = readSurfaceMesh("small_disk.obj"); // this line goes well
	// Compute distance
	VertexData<double> distToSource = exactGeodesicDistance(*mesh, *geometry, mesh->vertex(0));
	std::cout << distToSource.toVector();
	return EXIT_SUCCESS;
}

```

The mesh I am using is this [small_disk.obj](https://github.com/GeometryCollective/ddg-exercises/blob/main/input/small_disk.obj)

**Comment by MarkGillespie** [comment]
Thanks for pointing this out! I think #120 should fix these issues, but please let me know if things keep going wrong

(If you're curious, your diagnosis of the issue was exactly right: the manifold and nonmanifold surface loaders construct halfedge meshes slightly differently, and this made the propagate code recurse indefinitely on manifold meshes with boundary)

**Comment by henryliuw** [comment]
Thanks for your quick help! 

Just being curious, how does the manifold surface different from the nonmanifold? Do they construct the geometry with a reindexing of halfedges/vertices/etc. or does the manifold maintains more variables that somehow caused the error?

**Comment by MarkGillespie** [comment]
Yeah, it all comes down to how the halfedges are indexed. In geometry-central, manifold meshes use the "implicit twin convention", meaning that all halfedges must have exactly one twin halfedge (more details [in the docs here](https://geometry-central.net/surface/surface_mesh/internals/#exterior-boundary-elements)). This means that boundary halfedges also have a twin, even though there's no face on the other side. In the buggy code, I forgot to check for these phantom boundary halfdges in the `propagate` function, and called it even on boundary loops, which somehow made it run forever. But nonmanfold meshes don't use the implicit twin convention, so they don't create extra halfedges for boundary edges and you never need to check for them

**Comment by henryliuw** [comment]
Wow! that's an interesting convention, thanks for your reply!
