### ISSUE TITLE
2D Finite element and Jacobian calculation

### ISSUE THREAD

**Issue by liubenyuan** [nmwsharp/geometry-central#12]
Hi, I found this project really interesting.

I want to use halfedge mesh for Finite element and Jacobian calculation on 2D domain, where $\Delta \sigma \Delta f = 0$ and a boundary valued problem is solved. The Jacobian is defined as the first order derivative with respect to the conductivity $\sigma$. 

Can geometry central represent 2D meshes (triangles) efficiently? as well as the calculation on 2D meshes?

Best.

**Comment by nmwsharp** [comment]
Hi, thanks for your interest!

geometry-central can certainly represent 2D triangle meshes, though there are fewer already-implemented utilities in 2D compared to 3D. The connectivity is treated separately from the geometry in this library, so you can create a `HalfedgeMesh` as usual, then store your geometry via a `VertexData<Vector2>` and compute any relevant quantities from it.

In terms of solving your PDE, this is mostly up to the user. Unlike fancy finite element libraries (like FEniCS), geometry-central does not provide many utilities for automatically building general FEM systems. So you could implement the system, but coding up the matrix elements is up to you. Two things geometry-central _does_ have, which might be useful, are:
- a discretization of the Laplacian matrix, which you could get via an `EdgeLengthGeometry`
- sparse linear solvers with nice wrapper
