### ISSUE TITLE
Quadratic programming in Geometry Central?

### ISSUE THREAD

**Issue by lukkio88** [nmwsharp/geometry-central#121]
Hi,

I am using Geometry Central for a project of mine. I wonder if the library provides any quadratic programming solver (constrained) or if there's some specific external library you would suggest to use. I think either dlib or libigl might be ok, I would prefer though not having another geometry library linked in my project though.

**Comment by keenancrane** [comment]
GC is generally agnostic to the kind of solver you use; it’s main purpose is to encode geometry (though some of the provided algorithms do indeed rely on a linear solver…)

Personally I’ve had luck with Mosek, but it really depends on your needs & licensing constraints.

**Comment by lukkio88** [comment]
Thank you for your reply.
I assume by linear solver you mainly mean linear system solver, not linear programming solver.

Can you confirm?

**Comment by keenancrane** [comment]
Correct.

**Comment by nmwsharp** [comment]
libigl's [quadprog](https://github.com/libigl/libigl/blob/main/include/igl/copyleft/quadprog.h) built-in routine is pretty easy to use!

It is probably less powerful than MOSEK etc, and is under a more restrictive license than the rest of libigl, but still might be enough to get you started. One nice thing about libigl's architecture is that it's very easy to use just one piece of libigl without using all of it.

**Comment by nmwsharp** [comment]
I'm closing this now assuming that it is answered, feel free to reopen if there's more to discuss!
