### ISSUE TITLE
Confused about edge dihedral angles.

### ISSUE THREAD

**Issue by Victorlouisdg** [nmwsharp/geometry-central#132]
Hi, I've just started using geometry-central and got a little confused about the result I was getting for the edge dihedral angles. Below is an example image of the results I'm getting on my meshes.

- **The result I expected**: angles close to 0 everywhere, except for the bend in the shoulder. There I would expect the angles to be either all negative or all positive.
- **The result I got**: The angles in the bend seem to be almost randomly varying between positive and negative.

My first thought was that my face normals might be inconsistent, however, as you can see in the other image below, the normals seem fine. Maybe there's another problem with my mesh?

I've attached the `.obj` of my mesh and included a minimal reproduction below.

Image 1: (Confusing ) edge dihedral angles
![image](https://user-images.githubusercontent.com/23340946/202414189-4a8fae87-66c1-4f07-94e1-48c4c84a325d.png)

Image 2: Face normals
![image](https://user-images.githubusercontent.com/23340946/202415413-7ca1abd5-3cd7-4a40-b697-466fa1a1303a.png)

Minimal reproduction:
```c++
#include "geometrycentral/surface/direction_fields.h"
#include "geometrycentral/surface/manifold_surface_mesh.h"
#include "geometrycentral/surface/meshio.h"
#include "geometrycentral/surface/surface_mesh.h"
#include "polyscope/polyscope.h"
#include "polyscope/surface_mesh.h"

using namespace geometrycentral;
using namespace geometrycentral::surface;

int main() {
  std::unique_ptr<SurfaceMesh> mesh;
  std::unique_ptr<VertexPositionGeometry> geometry;
  std::tie(mesh, geometry) =
      readManifoldSurfaceMesh("../meshes/shirt_smooth.obj");

  polyscope::init();

  auto *psMesh = polyscope::registerSurfaceMesh(
      "my mesh", geometry->vertexPositions, mesh->getFaceVertexList());

  geometry->requireFaceNormals();
  geometry->requireEdgeDihedralAngles();
  psMesh->addFaceVectorQuantity("normals", geometry->faceNormals);
  psMesh->addEdgeScalarQuantity("dihedral_angles", geometry->edgeDihedralAngles);

  polyscope::show();
}
```

[shirt_smooth.zip](https://github.com/nmwsharp/geometry-central/files/10030327/shirt_smooth.zip)

**Comment by nmwsharp** [comment]
Hi! Thanks for the well-explained issue and images. I'm pretty sure what's happening here is that this is the totally correct result, it's just a bit unintuitive. 

When a seemingly-smooth mesh is bent along a seemingly-smooth deformation, you can actually get funky local bending on individual elements, because the edges do not align with the bending direction. Notice that in your image there's a trend where edges aligned with the bending have the pretty consistent negative dihedral angles you'd expect, but it's only those perpendicular to the bending sometimes have funky positive dihedral angles.

Does that make sense? Let me know if not, or if you suspect there is a bug here.

**Comment by Victorlouisdg** [comment]
Thanks for explaining, that does make a lot of sense! In the screenshot below you can see it even more clearly. The edges that are close to being parallel to the bending direction have negative dihedral angles, while the edges nearly orthogonal to the bending direction can be slightly positive. There's even an edge with a positive dihedral angle of 0.135 radians, which is almost 8 degrees! I didn't know this could happen, TIL. :) 

![image](https://user-images.githubusercontent.com/23340946/203403649-8db8342e-51e8-489d-bd21-b1714b400309.png)
