### ISSUE TITLE
Using Geometry Central for Solving Heat Equation on Point Cloud 

### ISSUE THREAD

**Issue by cemoke** [nmwsharp/geometry-central#154]
Hi,

First of all, thank you for this great library. I am a fresh Ph.D. student in robotics and planning to use the library to solve the heat equation on point clouds at relatively high speeds. I am aware that the primary use of the heat equation in this library is to compute geodesic distances, but for my use case what I need is the temperature field on the point cloud after some timestep.

As a Python developer who is not experienced with computer graphics, this library is huge for me, and I am having a bit rough time understanding where to look exactly for the skeleton of the heat equation solver on point clouds.
 
I would be glad if you can guide me in that regard.

Best regards.

**Comment by nmwsharp** [comment]
Check out Potpourri3d for python bindings for many of these functions, including short-time heat flow on point clouds!

However, neither this library nor that one has direct support for solving more general heat equations. We can build you the Laplace operator, but beyond that it is up to you to set up and solve the systems. In particular, these short-time methods always use a single backwards-Euler timestep, whereas for solving more general heat equations you almost certainly want multiple timesteps.
