### ISSUE TITLE
Compatibility with LVR2 https://github.com/uos/lvr2

### ISSUE THREAD

**Issue by Stblacq** [nmwsharp/geometry-central#172]
Say I have a mesh loaded with lvr2 https://github.com/uos/lvr2, or another library and a path ( a vector of edges or vertices) how can I use the flipOut  algorithm to shorten the path

**Comment by nmwsharp** [comment]
You'd need to write a little code to construct a geometry-central SurfaceMesh object https://geometry-central.net/surface/surface_mesh/basics/#constructors using this library's datatypes, and then invoke the FlipOut function here https://geometry-central.net/surface/algorithms/flip_geodesics/. 

(closing old issue, feel free to reopen if there are further questions)
