### ISSUE TITLE
Weird behavior in PoissonDiskSampler

### ISSUE THREAD

**Issue by dyollb** [nmwsharp/geometry-central#184]
I am trying to use the PoissonDiskSampler to sample a triangle mesh with minimum sample distance `distance`:

```cpp
    gc::surface::SimplePolygonMesh simpleMesh;
    for (const auto & t : qmesh.get_tris_buffer())
    {
        simpleMesh.polygons.push_back({t.inds[0], t.inds[1], t.inds[2]});
    }
    for (const auto & v : qmesh.get_verts_buffer())
    {
        simpleMesh.vertexCoordinates.push_back({v.x, v.y, v.z});
    }

    std::unique_ptr<gc::surface::ManifoldSurfaceMesh> mesh;
    std::unique_ptr<gc::surface::VertexPositionGeometry> geometry;
    // throws exception if input is non-manifold/invalid
    std::tie(mesh, geometry) = gc::surface::makeManifoldSurfaceMeshAndGeometry(simpleMesh.polygons, simpleMesh.vertexCoordinates);

    geometry->requireEdgeLengths();
    double meanEdgeLength = 0.;
    for (auto e : mesh->edges()) {
      meanEdgeLength += geometry->edgeLengths[e];
    }
    meanEdgeLength /= mesh->nEdges();
    geometry->unrequireEdgeLengths();

    gc::surface::PoissonDiskSampler sampler(*mesh, *geometry);
    auto samples = sampler.sample(distance / meanEdgeLength);

    std::vector<Vec3d> points;
    points.reserve(samples.size());
    for (auto& s: samples)
    {
        auto p = s.interpolate(geometry->vertexPositions);
        points.push_back({p.x, p.y, p.z});
    }
```

If I sample a (approximate) cube with edge length 40 (two triangles per cube face), I get following behavior:

| distance=4  | distance=2 | distance=1 |
| :---: | :---: | :---: |
| samples: 3 | samples: 22 | samples: 6559 |
| ![image](https://github.com/user-attachments/assets/99ab8f63-8b4c-4a5e-b6d0-d8aa0b6e6648)  | ![image](https://github.com/user-attachments/assets/7f878595-5108-4ec0-91d2-0754a6c2fdcd)  | ![image](https://github.com/user-attachments/assets/ae7e1323-be75-417e-ab1c-a0ce81b5efd4) |

Why is this happening? Am I doing something wrong?

**Comment by dyollb** [comment]
@nmwsharp Is this a bug or a user error?

Looking at the code I am wondering why the sqrt of the minDist is used to create new samples here:
https://github.com/nmwsharp/geometry-central/blob/45321a7e332c365629dfec2adfc51069f1ac2047/src/surface/poisson_disk_sampler.cpp#L93

**Comment by nzfeng** [comment]
Hey @dyollb, thanks for making a pull request! I've been meaning to correct this issue for a while now. Totally agree it doesn't usually make too much sense for the min distance to be in terms of edge length. 

And yeah, line 93 looks like a bug -- thank you for catching it! 

I'll get back to you on your PR!
