### ISSUE TITLE
Integrating the Surface Simplification using Intrinsic Error Metrics by Liu et. al. or Signed Heat Method detailed by Feng and Crane papers?

### ISSUE THREAD

**Issue by JeffreyLayton** [nmwsharp/geometry-central#187]
Hey, 

So after reading the papers on [Surface Simplification](https://www.cs.cmu.edu/~kmcrane/Projects/IntrinsicErrorMetric/IntrinsicErrorMetric.pdf) and [Signed Heat Method](https://nzfeng.github.io/research/SignedHeatMethod/index.html), these two methods would be fantastic for my project on surface simulations. Is there any discussion of integrating these papers into the library in the near  #future?

Regards,
Jeffrey Layton

**Comment by nzfeng** [comment]
The Signed Heat Method was just added in 167923f! Documentation is now up for the [surface mesh solver](https://geometry-central.net/surface/algorithms/signed_heat_method/) and [point cloud solver](https://geometry-central.net/pointcloud/algorithms/heat_solver/#signed-geodesic-distance).

You may have seen Derek's code for intrinsic simplification [here](https://github.com/HTDerekLiu/intrinsic-simplification), though I don't personally know when/if it's coming to geometry-central. But Derek's code uses [libigl](https://libigl.github.io/), which is another good mesh processing library.

**Comment by nmwsharp** [comment]
There are no immediate plans for incorporating the Intrinsic Simplification code into geometry-central, but it would certainly be great to do so if anyone ever has the time!
