### ISSUE TITLE
Path issue when linking on macOS

### ISSUE THREAD

**Issue by dcoeurjo** [nmwsharp/geometry-central#20]
When linking to geometry-central on macOS (e.g. using https://github.com/nmwsharp/gc-polyscope-project-template), cmake/make is complaining about  `-lm` and `-dl` targets:

```
[ 95%] Built target geometry-central
make[2]: *** No rule to make target `../deps/geometry-central/deps/-lm', needed by `bin/gc_project'.
make[2]: *** No rule to make target `../deps/geometry-central/deps/-ldl', needed by `bin/gc_project'.
make[2]: Target `CMakeFiles/gc_project.dir/build' not remade because of errors.
```

The problem comes from path variables in cmake and when I comment the line  168 of `geometry-central/deps/CMakeLists.txt`:

       convert_paths_to_absolute(GC_DEP_LIBRARIES)
==>

      #convert_paths_to_absolute(GC_DEP_LIBRARIES)

the problem disappears.

(and no problem on linux)

**Comment by nmwsharp** [comment]
OK! #19 was just merged. Please pull from master and let me know if that fixes the issue you observed.

**Comment by dcoeurjo** [comment]
👏👏
I’ll have a look ASAP thx

**Comment by dcoeurjo** [comment]
Works perfectly on my projects. Thanks!

**Comment by nmwsharp** [comment]
Glad to hear! @ctlee did the hard work and deserves the thanks! 😄
