### ISSUE TITLE
Is Suitesparse a requirement?

### ISSUE THREAD

**Issue by mhogg** [nmwsharp/geometry-central#26]
Hi,

It is not clear from your documentation if Suitesparse is actually a requirement, or just a nice to have. That is, if Suitesparse is not available on the system, will Eigen be used instead?

At this stage I would like to check out your geodesic distance features that use the different heat methods, but I will need to run it on Windows. Since Suitesparse is quite difficult to install on Windows, I was hoping to avoid that if not absolutely necessary.

Thanks for your time,
Michael

**Comment by nmwsharp** [comment]
Yes, this is exactly the purpose Eigen/Suitesparse wrappers. Eigen's sparse solvers will be used if Suitesparse is not found.

I'll add a sentence to the docs to make this more clear. Please reopen if you have any further questions!

**Comment by nmwsharp** [comment]
Text is now updated here: http://geometry-central.net/build/dependencies/#suitesparse
