### ISSUE TITLE
Computing geodesic path

### ISSUE THREAD

**Issue by lukkio88** [nmwsharp/geometry-central#31]
Hi,

Can geometry central given source and destination point on a 3D mesh represent somehow the geodesic path?
I can see this : https://github.com/nmwsharp/geometry-central/blob/master/include/geometrycentral/surface/exact_polyhedral_geodesics.h

But the description isn't to me 100% clear of what it does, it sounds however it might do the job.
Thank you

**Comment by nmwsharp** [comment]
Hi! No, this exact functionality isn't available in geometry-central right now (though it totally should be).

We previously had built-in implementation of the Improved Chen Han (ICH) algorithm to offer this, but it got dropped in an upgrade. I should be able to restore it soon.

(If you're looking for quick alternatives, this codebase https://code.google.com/archive/p/geodesic/ is often used for that task---you'll find it wrapped several other libraries. It's a bit old, but gets the job done :) )

**Comment by lukkio88** [comment]
_> We previously had built-in implementation of the Improved Chen Han (ICH) algorithm to offer this, but it got dropped in an upgrade. I should be able to restore it soon._

How soon are we talking about? If not soon enough is there maybe a version of the project that has this available?

**Comment by nmwsharp** [comment]
> How soon are we talking about?

I probably shouldn't promise anything :) Too much going on!

I think the best way I can help is to [share some wrappers](https://gist.github.com/nmwsharp/6f1b803db5357dbe71617b6a071e5afd) that I've used in the past to interface geometry-central with the [Kirsanov geodesic codebase](https://code.google.com/archive/p/geodesic/). It shouldn't be too hard to get that compiling, and it's tried-and-tested. The wrapper includes a function to report the paths themselves, as a sequence of 3D points.

**Comment by lukkio88** [comment]
I didn't mean to pressure you. I'm pretty sure you're busy. But I'm currently using Libigl and I was wondering if I should replace it with Geometry-Central

**Comment by nmwsharp** [comment]
No worries, I'm happy to help! 😄 

Closing for now, feel free to reopen as needed.

**Comment by mhogg** [comment]
I realise that this issue is closed, but wanted to add that [pygeodesic](https://pypi.org/project/pygeodesic/) is able to compute the geodesic path, not just the geodesic distance. It is a Cython wrapper around the Kirsanov codebase that Nick mentions above. Note that I am the author of pygeodesic.

For me, I will continue to use pygeodesic until Nick is able to update https://pypi.org/project/potpourri3d/ with a geodesic path based output on the heat or vector heat methods.

**Comment by nmwsharp** [comment]
pygeodesic looks awesome, thank you for sharing!
