### ISSUE TITLE
Add convenience accessors/iterators for Edge endpoints

### ISSUE THREAD

**Issue by keenancrane** [nmwsharp/geometry-central#37]
This may fall under the heading of "too much sugar", but it could be nice to have accessors for the two endpoints of an edge.  Currently there are neither accessors like `tip()` and `tail()`, nor is there an iterator `Edge::adjacentVertices()`.  The latter is of course useful when you need to do the same thing at both endpoints.  The former is natural if you want to, say, average values at the two endpoints, or (more exotic example) perform a conformal scaling.  Of course `tip` and `tail` make sense only for an oriented edge, but perhaps `Edge::firstVertex()` and `Edge::secondVertex()` (or similar) could be used.

**Comment by nmwsharp** [comment]
Added 2e5b98ee9ce8b6008abda792766f7f39154ffe25.

Includes both `Edge::firstVertex()` and `Edge::secondVertex()`, as well as an iterator `Edge::adjacentVertices()` (which just returns a `std::array<Vertex,2>`).
