### ISSUE TITLE
Add diamond accessors for Edge

### ISSUE THREAD

**Issue by keenancrane** [nmwsharp/geometry-central#38]
A fairly common stencil for edges in a (manifold) triangle mesh is the boundary of the "diamond" made by the two incident triangles.  Maybe this is getting too specialized.  But it might not be so bad to have a method `Edge::diamondBoundary()` that iterates over `e.halfedge().next()`, `e.halfedge.next().next()`, `e.halfedge.twin().next()`, and `e.halfedge().twin().next().next()`.  This list is conceptually simple, but currently translates to some pretty ugly code when written inline.

One simple implementation, perhaps, is to just construct and return this list (rather than defining a new iterator class):

```
array<Edge,4> diamondBoundary( Edge e )
{
   Halfedge h = e.halfedge();
   Halfedge hN = h.next();
   Halfedge hT = h.twin();
   Halfedge hTN = hT.next();
   return { hN.edge(), hN.next().edge(), hTN.edge(), hTN.next().edge() };
}
```

Perhaps, again, this is getting too specialized and it is better to just let someone write this code themselves.  But adding additional "convenience" neighborhoods doesn't seem to add too much glut to the code/documentation, and will only make other code leaner, cleaner, and less error-prone.

**Comment by keenancrane** [comment]
Building an explicit array for this particularly helpful, because it allows one to write things like

```
std::tie( jk, ki, il, lj ) = diamondBoundary( ij );
```

In other words, it allows one to turn obnoxious halfedge references (or indexed accessed into a list) into something that's easy to read and reference.

**Comment by nmwsharp** [comment]
👍 

One additional thought: the iterator version is nice since it scales to non-edge-manifold meshes, where there might by many vertices in the diamond. This would be quite straightforward to implement using the same pattern as existing iterators.

**Comment by nmwsharp** [comment]
Added in 94eb7ea37533cccb168f44dd315ad04a50aeb44b.

I just went with  `std::array<Halfedge, 4> Edge::diamondBoundary()` for now. It throws an exception if you call it on a non-triangular/boundary/nonmanifold edge. 

The more general nonmanifold (etc.) iterators are easily written in terms of other existing iterators, so I think those are less crucial.
