### ISSUE TITLE
Unable to include pointcloud headers in other projects

### ISSUE THREAD

**Issue by cbw36** [nmwsharp/geometry-central#73]
I am trying to run the pointcloud examples from http://geometry-central.net/pointcloud/basics. I am unable to compile the examples, though, because it cannot find the pointcloud headers. I am able to compile with surface or utility headers, so it is able to access the geometry-central library.

I noticed that the geometry-central src CMakeLists does not include pointcloud headers. Even after adding them, the pointcloud examples still don't compile.

**Comment by nmwsharp** [comment]
Uh oh, that sounds bad. Thanks for reporting!

I haven't seen this on my end (and have used the code for other projects), so I'm not really sure what's going on. Can you be more specific about how compilation fails? For instance, can it not find the header files? Or do you get some other error?

> geometry-central src CMakeLists

Ah, yeah, we should add those there. However, this probably isn't the cause of a compilation failure; headers don't actually need to be in CMake source listing since there's nothing to compile for them. It's just useful to put them there as an informational property---for instance, headers only show up in the Visual Studio explorer sidebar if they are listed in the CMakeLists file.

**Comment by cbw36** [comment]
Thanks for the help! Yeah, here's the error exactly:

fatal error: geometrycentral/pointcloud/point_cloud.h: No such file or directory
 #include "geometrycentral/pointcloud/point_cloud.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/pointcloud_tutorial.dir/build.make:62: recipe for target 'CMakeFiles/pointcloud_tutorial.dir/src/pointcloud_tutorial.cpp.o' failed
make[2]: *** [CMakeFiles/pointcloud_tutorial.dir/src/pointcloud_tutorial.cpp.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/pointcloud_tutorial.dir/all' failed
make[1]: *** [CMakeFiles/pointcloud_tutorial.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 97%] Building CXX object CMakeFiles/template_main.dir/src/template_main.cpp.o
[ 98%] Building CXX object CMakeFiles/mesh_tutorial.dir/src/mesh_tutorial.cpp.o
[ 98%] Linking CXX executable bin/mesh_tutorial
[ 98%] Built target mesh_tutorial
[ 99%] Linking CXX executable bin/template_main
[ 99%] Built target template_main
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by nmwsharp** [comment]
Great, I'm sure we can sort this out.

Just to be clear, is the header file itself actually present in your local copy of the library? I.e. does `geometrycentral/include/geometrycentral/pointcloud/point_cloud.h` exist?

If so, then perhaps there is some issue with include paths...?

**Comment by cbw36** [comment]
Yup it does exist.

**Comment by nmwsharp** [comment]
OH also it looks like you're compiling with `make`, so you could invoke it like `make VERBOSE=1` to get verbose output, then share that here. That will give a full command line build string so we can see what's up.

**Comment by cbw36** [comment]
yeah I already tried a clean build after deleting the whole /build directory, but I tried again.

Also it may be worthwhile to mention that I am using the gc-polyscope-project-template. So the CMakeLists is the same and the only changes I made were adding new executables. 


[CMakeLists.txt](https://github.com/nmwsharp/geometry-central/files/5960509/CMakeLists.txt)
[make verbose output.txt](https://github.com/nmwsharp/geometry-central/files/5960528/make.verbose.output.txt)

**Comment by nmwsharp** [comment]
I really do not know what's up then. I just did the following steps to try to reproduce:

- `git clone --recursive git@github.com:nmwsharp/gc-polyscope-project-template.git`
- `cd` in to `deps/geometry-central` and run `git pull origin master` to get the latest version (the project template is slightly out of date)
- add the line `#include "geometrycentral/pointcloud/point_cloud.h"` to `src/main.cpp`
- configure and build with `mkdir build && cd build && cmake .. && make` from the project root

and it builds fine. Can you try running those steps in a clean directory to see if they work on your end? I'm not sure what else to check.

**Comment by cbw36** [comment]
It works! Seems like the problem was that I didn't pull the latest version of the deps repos, so the pointcloud files were not there. I was looking for the pointcloud headers in my geometry-central library, because I forgot there was a deps directory where it was looking.

Thanks for your help!

**Comment by nmwsharp** [comment]
Ah, so glad there's some sane explanation. Git submodules are so confusing for these things, but unfortunately I don't know a better solution. Happy I could help!
