### ISSUE TITLE
Convert Vectors from direction fields to real World space

### ISSUE THREAD

**Issue by MathSigmamu** [nmwsharp/geometry-central#78]
Hi I might just not have understood things correctly but I was wondering if there was a way or a plan to implement a method to convert the Vector2 vectors from the Vector field algorithms to real world Vector3 vectors without using polyscope? Or if there is a way to get the real world Vector3 from polyscope ?

**Comment by nmwsharp** [comment]
Hi!

These tangent vectors are defined in a local basis in each vertex/face. You can get these local bases from the [geometry object "tangent basis" quantities](http://geometry-central.net/surface/geometry/quantities/#vertex-tangent-spaces).

So for instance, to convert a tangent vector field at vertices to equivalent 3D vectors you could do something like

```cpp
// your data, populated somehow
SurfaceMesh mesh;
VertexPositionGeometry geom;
VertexData<Vector2> myTangentVectorField;

// convert to 3D vectors
VertexData<Vector3> my3DVectorField(mesh);
geometry.requireFaceTangentBasis();

for(Vertex v : mesh.vertices()) {
  Vector2 field = myTangentVectorField[v];

  Vector3 basisX = geometry.vertexTangentBasis[v];
  Vector3 basisY = geometry.vertexTangentBasis[v];

  Vector3 fieldInWorldCoords = basisX * field.x + basisY * field.y;
  my3DVectorField[v] = fieldInWorldCoords;
}
```

**Comment by keenancrane** [comment]
I agree it would not be bad to wrap what @nmwsharp just wrote into a convenience routine.

**Comment by MathSigmamu** [comment]
Hi Nicholas 

Thank you so much for that information it solved my problem perfectly!
