### ISSUE TITLE
need versioning

### ISSUE THREAD

**Issue by Orbots** [nmwsharp/geometry-central#91]
Could you add version tracking for releases?  

Makes it easier to use in a production environment.

Here's a nice example of version tracking for a release:  https://github.com/libigl/libigl/releases/tag/v2.3.0

**Comment by nmwsharp** [comment]
Ah you're totally right, not sure how we never tagged any releases for this library. I guess v1.0 always feels just around the corner!

I went ahead and tagged the current version as `v0.1.0` for now. In the near future we can bump to `v1.0` and get some changelogs going.

https://github.com/nmwsharp/geometry-central/releases/tag/v0.1.0

**Comment by ytausch** [comment]
Hi, I added your (very cool) library to the conda-forge packaging ecosystem: [link](https://prefix.dev/channels/conda-forge/packages/geometry-central)

Also, I appreciate that you made the 0.1.0 release! Could you consider making releases more often? This would semi-automatically update the conda-forge package and enable users to use the latest features of your library! 🚀
